asbiin/laravel-webauthn

- composer.json
- composer.lock
- src/Services/Webauthn/PublicKeyCredentialValidator.php
> feat: remove diactoros

- tests/Fake/FakeCredentialRepository.php
Use class version of `array_has` helper
> chore: use string and array classes

- CHANGELOG.md
- src/Http/Controllers/WebauthnController.php
- src/WebauthnServiceProvider.php
Add a new route 'webauthn.destroy'.
Rename the controller method.
> fix: name the destroy route

- CHANGELOG.md
- composer.json
- composer.lock
- src/Services/Webauthn/AbstractValidatorFactory.php
Remove Guzzle6 library dependency. Use discovery to get a HttpClient.
> fix: remove Guzzle6 direct dependency

- resources/views/register.blade.php
- src/Http/Controllers/WebauthnController.php
When creating a key, add an input "name" to precise the name of the key we add.
> Add a way to put a name to a new key

- .circleci/config.yml
> chore: fix ci

- CHANGELOG.md
- database/migrations/2019_03_29_163611_add_webauthn.php
> fix: use bigInteger for foreign key reference

- CHANGELOG.md
- composer.json
- composer.lock
> chore(deps): upgrade for laravel 6.x

- CHANGELOG.md
- composer.json
- composer.lock
- sonar-project.properties
- src/Models/WebauthnKey.php
- tests/Unit/PublishCommandTest.php
Fixed the aaguid/uuid decode if there is no value.
Add suggestion for web-token/jwt-signature-algorithm* installation.
> fix: fix Uuid decode & update dependencies

- .github/workflows/workflow.yml
- CHANGELOG.md
- composer.json
- composer.lock
- phpstan.neon
- src/Models/WebauthnKey.php
- src/Services/Webauthn/AbstractOptionsFactory.php
- src/Services/Webauthn/CredentialRepository.php
- src/Services/Webauthn/PublicKeyCredentialCreationOptionsFactory.php
- src/Services/Webauthn/PublicKeyCredentialRequestOptionsFactory.php
- tests/Unit/PublishCommandTest.php
> Support Laravel 7 and upper

- .github/workflows/static.yml
- .github/workflows/tests.yml
- src/Services/WebauthnRepository.php
> build: test with php 8.1

- src/Http/Responses/RegisterViewResponse.php
Typo in config->get breaking the webauthn/keys/create
> fix: fix RegisterViewResponse

- .github/workflows/tests.yml
- composer.json
> feat: require php 8.1+

- src/Services/Webauthn.php
- src/Services/Webauthn/CredentialAttestationValidator.php
- tests/Unit/Models/Casts/Base64Test.php
- tests/Unit/Services/WebauthnTest.php
- tests/database/factories/WebauthnKeyFactory.php
> fix: fix authenticatorData format

- src/Services/Webauthn.php
Fix for #404 replicating fix for #401.
> fix: fix attestation validation by re-encoding response.clientDataJSON

- resources/views/authenticate.blade.php
- resources/views/register.blade.php
> fix: fix axios integrity in blade views

- config/webauthn.php
> feat: replace deprecated algorithm

- src/Services/Webauthn/CreationOptionsFactory.php
- src/Services/Webauthn/CredentialAssertionValidator.php
- src/Services/Webauthn/CredentialAttestationValidator.php
- src/Services/Webauthn/RequestOptionsFactory.php
> fix: fix serialization

- src/Listeners/LoginViaRemember.php
This allows using:
```php
Event::subscribe(LoginViaRemember::class);
```
> feat: add LoginViaRemember subscribe method

- src/Services/Webauthn/OptionsFactory.php
> docs: fix timeout doc

- resources/views/register.blade.php
> fix: remove start call on register page

- src/WebauthnServiceProvider.php
This improves support of userless/non-userless
> fix: remove override of configuration
